### ISSUE TITLE
GH API requests timing out

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/kpis#55]
Great work in https://github.com/2i2c-org/kpis/pull/54 !

Unfortunately, the website deployment was not complete because I think the GH API calls were timing out in the [GH action](https://github.com/2i2c-org/kpis/actions/runs/11452935744/job/31864589933)

` http.client.RemoteDisconnected: Remote end closed connection without response`

**Comment by choldgraf** [comment]
This seems to be a temporary issue, and re-builds haven't run into this!
